[package]
name = "sorcery"
version = "0.1.0"
authors = ["conner bryan <conner@amps.io>"]
description = "ui components"
license = "MIT"
edition = "2018"

[dependencies]
thiserror = "^1.0"
sorcery-codegen = { path = "../sorcery-codegen" }
dyn-clone = "^1.0"
generational-arena = "0.2.8"
tracing = "0.1"
crossbeam-channel = "^0.5"

[dev-dependencies]
tracing-subscriber = {version = "0.1.6", features = ["chrono", "env-filter", "fmt"]}
test-env-log = {version = "^0.2", features=["trace"], default-features=false}